### ISSUE TITLE
Crash on starting proto file generation

### ISSUE THREAD

**Issue by trueromanus** [dart-lang/protobuf#370]
Hi and thanks for nice tool for generation grpc services.

I ran into a problem after updating for the last time flutter/dart.

I'm use cli command as example below
```
protoc --dart_out=grpc:lib\protoServices --proto_path=C:\rurk\work\v3pure\gRPC.Mobile Protos/wfm.proto
```
I try downgrade or upgrade version protoc_plugin but this don't change anything.  
All my proto files not generating. Error log below.
```
Unhandled exception:
NoSuchMethodError: Closure call with mismatched arguments: function '_memberNamesSuffix'
Receiver: Closure: (_SyncIterator<String>) => bool
Tried calling: _memberNamesSuffix()
Found: _memberNamesSuffix(_SyncIterator<String>) => bool
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      _SyncIterable.iterator (dart:core-patch/core_patch.dart:117:45)
#2      disambiguateName (package:protoc_plugin/names.dart:166:27)
#3      _unusedMemberNames (package:protoc_plugin/names.dart:419:17)
#4      messageMemberNames (package:protoc_plugin/names.dart:291:11)
#5      MessageGenerator.resolve (package:protoc_plugin/message_generator.dart:187:27)
#6      FileGenerator.resolve (package:protoc_plugin/file_generator.dart:183:9)
#7      link (package:protoc_plugin/linker.dart:24:7)
#8      CodeGenerator.generate.<anonymous closure> (package:protoc_plugin/code_generator.dart:92:7)
#9      _RootZone.runUnary (dart:async/zone.dart:1450:54)
#10     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#11     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#12     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#13     Future._complete (dart:async/future_impl.dart:519:7)
#14     Stream.fold.<anonymous closure> (dart:async/stream.dart:776:14)
#15     _RootZone.runGuarded (dart:async/zone.dart:1372:10)
#16     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:410:13)
#17     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:420:15)
#18     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:305:7)
#19     _SyncStreamControllerDispatch._sendDone (dart:async/stream_controller.dart:792:19)
#20     _StreamController._closeUnchecked (dart:async/stream_controller.dart:644:7)
#21     _StreamController.close (dart:async/stream_controller.dart:637:5)
#23     _RootZone.runUnaryGuarded (dart:async/zone.dart:1384:10)
#24     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
#25     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:285:7)
#26     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:784:19)
#27     _StreamController._add (dart:async/stream_controller.dart:655:7)
#28     _StreamController.add (dart:async/stream_controller.dart:597:5)
#29     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1563:35)
#30     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:1045:18)
#31     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#32     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#33     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#34     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
--dart_out: protoc-gen-dart: Plugin failed with status code 255.
```

Protoc_plugin installed globally.
Dart version
```
Dart VM version: 2.9.0-9.0.dev.flutter-40f7a11d89 (be) (Mon May 18 12:22:50 2020 +0000) on "windows_x64"
```

What to do with this problem? Any ideas?

**Comment by trueromanus** [comment]
I'm closed.
My issue was new dart version change path to pub cache from dart folder to user folder.
